### ISSUE TITLE
Crash When Placing Slab in Water

### ISSUE THREAD

**Issue by emoace** [Micalobia/Full-Slabs#1]
Hello,

So glad to see a slab mod being actively supported!  I've been testing out vertical slabs with my modpack and ran into a problem.  Whenever I try to place a slab in water, in any orientation, the game crashes.  I have attached a crash log.

[crash-2021-02-25_19.53.32-client.txt](https://github.com/Micalobia/Full-Slabs/files/6046767/crash-2021-02-25_19.53.32-client.txt)

**Comment by Micalobia** [comment]
Thank you for the report, this *should* be fixed as of 1.1.2
