### ISSUE TITLE
Incompatibility with Better Nether and Better End mods.

### ISSUE THREAD

**Issue by K0-RR** [Micalobia/Full-Slabs#12]
https://hatebin.com/zfqvhuhrhg

**Comment by Micalobia** [comment]
I can't even launch the game with these mods to start with tbh, giving an error that doesn't have anything to do with my mod, so that's fun. I'll look into it as soon as I can, once I get the game to launch it shouldn't be too bad a fix

**Comment by SleepyTonia** [comment]
https://github.com/paulevsGitch/BetterEnd/issues/47#issuecomment-767589493
Is there a way I could be of help? This seems to be out of my league and I'm sorry to pester you some more…
But I could provide whatever logs you'd need if you pointed me in the right direction
