### ISSUE TITLE
[Feature request] Placing torches/full blocks on slabs.

### ISSUE THREAD

**Issue by K0-RR** [Micalobia/Full-Slabs#15]
![image](https://user-images.githubusercontent.com/43277609/114923660-6202ce00-9e2d-11eb-9cb7-1c8d1706cbe1.png)

https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod this is forge only, something like this. I'm requesting this because I thought if you managed to make various slabs placeable on each other then this could work similarly.
Could it be possible to place full blocks on top of slabs?

**Comment by Micalobia** [comment]
This is an interesting idea and something I can look into for sure.
Placing full slabs onto blocks probably can't happen, although I've been thinking of making another mod that adds a lot more slabs, in general, to make up for the lack of certain blocks having slabs, if that would be wanted.

**Comment by K0-RR** [comment]
And snow because this look so bad...
![image](https://user-images.githubusercontent.com/43277609/116779766-9a82e880-aa78-11eb-997f-e41515c129d7.png)

**Comment by Micalobia** [comment]
Wanted to give an update on this, it's about halfway working atm
It needs a little more work and some polish, but it visually works.

The blocks that are allowed are in a configuration file, where you can configure which block states can attach to which slab states, that way if another mod adds something like another type of torch it's easy to add.

By default, it allows snow, carpet, moss carpet, torches/lanterns, and their soul counterparts.
