### ISSUE TITLE
Implement Server support

### ISSUE THREAD

**Issue by JoacoSlime** [Micalobia/Full-Slabs#2]
Everytime you try to load the mod in a Fabric server, throws a lot of class errors and the server crashes.
[crashlog.txt](https://github.com/Micalobia/Full-Slabs/files/6066584/crashlog.txt)

I thought it would be a nice feature that you could use this mod in a Fabric server.

**Comment by Micalobia** [comment]
Should be fixed in 1.2.0, which should be out in the next few minutes, thank you for the report!
