### ISSUE TITLE
Game crash exit code -1

### ISSUE THREAD

**Issue by vonrix** [Micalobia/Full-Slabs#21]
With the default MC renderer it appears to run just fine in a standalone world, however, with Sodium and Indium installed I get a game crash with exit code -1 in the standalone world.

It states: The game crashed whilst unexpected error
Error:
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError:
An unexpected critical error was encountered
Exit Code: -1

I do have a lot of mods currently installed. I don't know if it's an issue with one of them but it does work with the default MC renderer with all of the same mods installed.

I will try to copy the crash report.

Thanks for the mod. I hope that I'm able to use it on our server.
[MC crash report for Full Slabs.txt](https://github.com/Micalobia/Full-Slabs/files/6448339/MC.crash.report.for.Full.Slabs.txt)

**Comment by heyjudek** [comment]
I am using both Sodium and Indium and it works fine with Full slabs. Maybe it has to do with the version of Sodium/Indium you are using?
