### ISSUE TITLE
1.17.x

### ISSUE THREAD

**Issue by catgirldoll** [Micalobia/Full-Slabs#24]
I would love to see a 1.17.x update for this excellent mod!

**Comment by Micalobia** [comment]
Probably going to rewrite very large portions of this mod, as it's not *nearly* up to the standard I want it to be, and patching it wouldn't work long-term. Need to find the motivation to work on this one again, so it might not be soon (I'm also moving between states atm), so I'll keep posting here on any updates that come to mind that are relavant.

**Comment by Micalobia** [comment]
The first release is out, should be good to go!

**Comment by catgirldoll** [comment]
Yup, I noticed yesterday. Thank you for your excellent work!
