### ISSUE TITLE
[Suggestion] Improve placement hint

### ISSUE THREAD

**Issue by alexmozaidze** [Micalobia/Full-Slabs#26]
I like the idea of placement hint, but the hint just covers the whole texture of blocks, which is annoying. It would be nice if the semi-transparent white background was fully transparent, so it doesn't get in the way of the block's/slab's texture. Also, it would be cool if the hint would cut itself in the places where you can't click (like the side of a single vertical slab).

**Comment by Micalobia** [comment]
I'll look into this because I honestly agree. That feature is using Malilib, so it may take a moment to get to it, but I'll put it on my TODO list
