### ISSUE TITLE
Crashes with ConnectedTexturesMod

### ISSUE THREAD

**Issue by oxymoronjuan** [Micalobia/Full-Slabs#28]
[FullSlabs crash with CTM.txt](https://github.com/Micalobia/Full-Slabs/files/7230062/FullSlabs.crash.w.CTM.txt)
[FullSlabs crash after removal of CTM.txt](https://github.com/Micalobia/Full-Slabs/files/7230063/FullSlabs.crash.w.o.CTM.txt)

**Comment by Micalobia** [comment]
Which CTM Mod did you use? The latest version I could find was for 1.16.5, while this mod is 1.17.1

**Comment by Micalobia** [comment]
I'm going to close this issue once the issue is 30 days old, due to lack of reply.
