### ISSUE TITLE
Crash when placing Slabs on Grass, Seaweed, Ferns, and similar modded blocks

### ISSUE THREAD

**Issue by emoace** [Micalobia/Full-Slabs#3]
Hello,

I received a crash when I tried placing a slab on a piece of grass, and the block decorations above.  I figure this is caused by a similar part of the code for replaceable blocks like grass, etc.

[crash-2021-03-02_14.05.26-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071526/crash-2021-03-02_14.05.26-client.txt)
[crash-2021-03-02_14.06.11-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071527/crash-2021-03-02_14.06.11-client.txt)
[crash-2021-03-02_14.10.47-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071528/crash-2021-03-02_14.10.47-client.txt)
[crash-2021-03-02_14.11.21-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071529/crash-2021-03-02_14.11.21-client.txt)
[crash-2021-03-02_14.11.52-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071530/crash-2021-03-02_14.11.52-client.txt)
[crash-2021-03-02_14.12.19-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071531/crash-2021-03-02_14.12.19-client.txt)
[crash-2021-03-02_13.52.01-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071532/crash-2021-03-02_13.52.01-client.txt)
[crash-2021-03-02_13.59.21-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071534/crash-2021-03-02_13.59.21-client.txt)
[crash-2021-03-02_14.01.31-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071535/crash-2021-03-02_14.01.31-client.txt)
[crash-2021-03-02_14.03.52-client.txt](https://github.com/Micalobia/Full-Slabs/files/6071536/crash-2021-03-02_14.03.52-client.txt)

**Comment by Micalobia** [comment]
It should be fixed in 1.2.0, which should be released within the next few minutes, thank you for the report!
