### ISSUE TITLE
Carpet gamerule breaks mixed slabs

### ISSUE THREAD

**Issue by Estrelaura** [Micalobia/Full-Slabs#34]
By having the movableBlockEntities rule from Carpet enabled, every attempt to make a mixed slab becomes a double stone slab instead. Orientation is kept the same, but the change into stone is permanent, as breaking half the block only returns a stone slab. No crash reports generated, tested with only both mods and Fabric API installed, only said gamerule enabled.

**Comment by Micalobia** [comment]
Interesting, I'll have to look into that. What's happening is that the double stone slab is the default state for a mixed slab in case something goes wrong, which moving it seems to trigger.

**Comment by Micalobia** [comment]
It's triggered by placing, not moving, by bad. Even weirder is that it doesn't move. Thank you for the report
