### ISSUE TITLE
Display bug on servers

### ISSUE THREAD

**Issue by xanthian** [Micalobia/Full-Slabs#37]
How it looks without Full Slabs installed (Client)
https://ibb.co/Msk1wwH

How it looks with Full Slabs installed (Client)
https://ibb.co/9hmNFSs

If I open the same world in Single Player, there is no issue.
Server is only running FabricAPI

Note, Full Slabs is not installed on server as will not launch with it.

**Comment by SplendidAlakey** [comment]
That's not a bug with the mod, that's just how MC behaves when a client is using a mod that adds new properties to vanilla blocks, that a server also doesn't use. The mod must be installed on both sides to function properly. 

#36 has already reported the server crash issue.

**Comment by xanthian** [comment]
ok, will close
