### ISSUE TITLE
Full Slabs 3.1.3 causes massive loading times when used in a large modpack

### ISSUE THREAD

**Issue by SplendidAlakey** [Micalobia/Full-Slabs#38]
**MC** 1.17.1
**FullSlabs** 3.1.3

When FullSlabs 3.1.3 is installed, it takes 10 minutes to load the game. Does not happen without FullSlabs and also didn't happen with FullSlabs 3.1.2. Also does not happen when 3.1.3 is used alone. Modlist can be found in both latest.log files, however, I can provide it separately, if needed.

Latest.log without FullSlabs: 
[removed]

Latest.log with FullSlabs:
[removed]

Since FullSlabs works fine on its own, I'll understand if this issue will not be fixed from your side.

**Comment by Micalobia** [comment]
If it doesn't happen with 3.1.2, then it has to do with the fix I made for the server-client desync in 3.1.3. I'll look into it, I don't expect it to be too difficult to fix

Basically, it's sorting a list every time a slab is added outside of vanilla, which I didn't think about the performance implications of. The fix *should* just be making it sort the list after all mods have loaded

**Comment by SplendidAlakey** [comment]
Just to be absolutely sure, I tested 3.1.2 again and yes, it loads normally.

Here's the log if it's of any use: [removed]

Thanks for looking into it!

**Comment by Micalobia** [comment]
So there's a new version called `3.1.4.exp1`, which *should* fix this issue but I'm not sure. If you could test it I would be grateful.

**Comment by SplendidAlakey** [comment]
Just tested it, the fix worked. Loaded in just 2 minutes, which is only like ~20 seconds longer than with 3.1.2, at which point it might just be a margin of error.

Thanks again!

**Comment by SplendidAlakey** [comment]
Upon further testing, it seems like loading times moved into the worldgen. It seems a bit faster anyway, though. When I loaded up my world it took 5 minutes to load. Tested it on a server as well, it loaded fast, but 50% of the blocks are invisible/wrong.

Client log: [removed]

What happens when joining a server:

![2021-10-02_16 00 45](https://user-images.githubusercontent.com/86702831/135719815-74f8169a-290f-44ca-8924-ee7d8fb0e27d.png)

What's weird is that most of it should be stone bricks, yet only some are invisible.

And this is how it should look like:

![2021-10-02_16 11 05](https://user-images.githubusercontent.com/86702831/135720091-54b7ebb3-e5f1-4e63-9f1b-5942dffcd2c0.png)

**Comment by Micalobia** [comment]
Are you using a mod pack that you've built off of, or is this just something you put together? Going to attempt to download it myself, just want to make sure 😄

**Comment by Micalobia** [comment]
Also thank you for being patient and continuing to reply, it's extremely helpful

**Comment by SplendidAlakey** [comment]
I put it together myself. You will need to edit MineGate config in order to be able to create worlds with this modpack, in its ini files or modmenu change "useMixins" to false. Other than that I don't think any of my custom configs matter, but, if needed, I can provide all of them.

And no problem at all, I love your mod, it's the best slab mod I've seen and I'd love to include it in my modpack.

**Comment by SplendidAlakey** [comment]
These 2 modpacks are the closest to what I have: [BetterMinecraft](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric) and [All of Fabric 4](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-4). But they don't have all the mods I do, and I don't use some mods that they include.

**Comment by Micalobia** [comment]
I've released a new experimental version if you could take a look

Thank you for reminding me to give explicit permission to use in modpacks, btw, that's a good idea

**Comment by SplendidAlakey** [comment]
The second experimental version works flawlessly so far. Initial start at about 2.5min, single-player world loaded in just ~30s. While connected to a server all blocks appear as intended. Amazing job! I will be keeping an eye out for any issues down the line, but this one can be considered fixed.

**Comment by Micalobia** [comment]
Cool beans, thank you for reporting!

**Comment by SplendidAlakey** [comment]
Ignore that, it was caused by some other mod (I think Eating animation).

~~Oh, just 1 thing I forgot to mention (not related to this issue at all, so let me know if it's worth opening another one for it) - Cut copper slab doesn't have the HUD elements when it's placed as a horizontal slab:~~

![2021-10-02_19 56 25](https://user-images.githubusercontent.com/86702831/135727289-b147b360-69c7-4b1f-b956-fc9cc5d353bc.png)

![2021-10-02_19 56 28](https://user-images.githubusercontent.com/86702831/135727293-a40a9360-77c1-4f0b-a6d3-a7afc9706c56.png)

~~I don't know if this is an issue with the experimental version or just in general with the mod.~~
