### ISSUE TITLE
Crashes when placing Promenade (mod) slabs on Vanilla slabs

### ISSUE THREAD

**Issue by ghost** [Micalobia/Full-Slabs#43]
After placing a slab of wood from the mod Promenade on a Cobblestone slab, the game crashed, and on return the chunk was invisible. after deleting the invisible promenade slab and relogging on the server, the chunk was back.

**Comment by ghost** [comment]
After a test, it actually crashes also when combining vanilla slabs, so I don't know what could be causing it.

**Comment by Micalobia** [comment]
Can you give a crashlog here? Either the file itself or a pastebin would be good

**Comment by SplendidAlakey** [comment]
Can't reproduce with any slabs from Promenade 2.1.2. I tried all 3 wood types from Promenade, combined it with cobblestone slabs, placed them vertically etc, no issues at all. Tested on both single-player and server.

**Comment by Micalobia** [comment]
I can't reproduce either, going to mark as outdated for now

**Comment by Micalobia** [comment]
I'm going to close this issue once the issue is 30 days old, due to lack of information and inability to reproduce.
