### ISSUE TITLE
Unsure if bug or not

### ISSUE THREAD

**Issue by xanthian** [Micalobia/Full-Slabs#51]
Since installing 3.2.0 getting lots of these messages when interacting with slabs.

[Server thread/INFO]: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2771, values=[bottom, top]} as it does not exist in Block{extshape:calcite_slab}
[Server thread/INFO]: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2771, values=[bottom, top]} as it does not exist in Block{extshape:calcite_slab}
[Server thread/INFO]: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2771, values=[bottom, top]} as it does not exist in Block{minecraft:birch_slab}
[Server thread/INFO]: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2771, values=[bottom, top]} as it does not exist in Block{minecraft:oak_slab}

edit . just to add, it doesnt seem to be having any negative impact from what I can see.

**Comment by Micalobia** [comment]
It's a bug I've patched but haven't release a version for, it technically makes the game crash if you put something like a torch in the bottom of a top slab. Haven't had the time to get around to things yet, work's been fun

Seen in Issue #47
