### ISSUE TITLE
Rendering issue placing slabs next to slabs on slabs

### ISSUE THREAD

**Issue by IdrisQe** [Micalobia/Full-Slabs#6]
(Using version 1.2.0 for 1.16.5)
So if I have a slab on top of another slab, and I try to put a slab beside said slab's top half, it causes the bottom half to stop rendering the affected face entirely, making a hole in the world. I haven't (yet) tested if this is an issue with just Full Slabs or if it's some kind of rendering incompatability (I am not using Optifine nor Sodium nor Canvas so I wouldn't imagine it is, but maybe)
![gif](https://user-images.githubusercontent.com/40530630/109933808-ab81ca00-7c80-11eb-8301-e0f7311ad656.gif)

**Comment by Micalobia** [comment]
Looking into it now; I had thought I fixed all the bugs like that, must not have checked enough, thank you for the report!

**Comment by Micalobia** [comment]
What mod are those slabs from? It might be a model error with those slabs, as I can't recreate it with vanilla ones.

**Comment by IdrisQe** [comment]
Edit: The Redwood ones are from Terrestria, and the Stripped Oak is from Lepton!

Edit 2: I... don't seem to be able to recreate the issue myself. I don't remember exactly how I had built that structure to cause said issue but it doesn't seem to be reoccuring in my testing? I have no idea. I'm confused.

EDIT 3: AHA! I got it happening again.

Edit 4: Some interesting things I noticed... Let me just record a couple gifs of it...

Edit 5: Reloaded the game... And now it isn't happening again.

Huhhh... Well the oak slabs are vanilla of course.
The red ones are Redwood from ... Terrestria or Traverse, I forget which admittedly.
And the stripped oak wood slabs are... Uhhhhhhh... I don't actually know, either Crumbs or Lepton probably?
I'll update this once I've launched the game and actually checked which mod adds which-

**Comment by IdrisQe** [comment]
Okay, so... It seems that every time I start the game, the combinations I previously tried no longer break, but if I turn a different direction, it breaks again. This makes zero sense, but explains why I couldn't recreate the issue before.

![gif](https://user-images.githubusercontent.com/40530630/110047923-9c902b80-7d03-11eb-80c9-f7ec9019911c.gif)

**Comment by Micalobia** [comment]
I'm going to be completely honest with you, I haven't the fainted idea why it's doing what it's doing, and for whatever reason, I can't recreate it. It might be another mod fudging it up, but you don't have any other rendering mods so I'm not sure what'd be causing it. If it happens again, try hitting `F3 + T` (it reloads textures normally, but it also regenerates the slab models for this mod), it *might* fix it, I've no idea. If you'd be willing to give a mod list, I'd be grateful, there isn't any rush though. Thank you for giving so much of your time

**Comment by IdrisQe** [comment]
It's okay! I do have some mods which MIGHT be affecting rendering in some ways but I don't think any specifically affect models or how block culling works? The problem is I can't really remove them to test because I went back in the world and now no matter what direction I try it in, the problem doesn't surface, even without changing any mods or configs.
And ideally I'd try to work it down to a smaller group of mods where the issue can be reliably reproduced, but I can't even reliably reproduce it with the exact same setup.
Thanks for the tip though, I'll definitely try that if it happens again!

Gosh though, just one more bizzare, inexplicable bug in this accursed modpack I put together...

_(seriously the number of seemingly sourceless bugs I've been getting is absurd... Including several that seem to solve themselves when I remove or add a certain _number_ of mods regardless of which mods they are. Like seriously, I take out one or two completely random mods that do barely anything, and suddenly I'm crashing with an error between one mod and... the logs can't even describe what the other thing is. I add back a different mod that does something else entirely, and it's fixed. I get a weird config incompatability, I remove a bunch of mods and test again, nothing. I add back mods one by one until it occurs again, take out the one that seemed to be the cause and put back in one that didn't affect it at all, put back another that didn't affect it at all, and suddenly it's back...)_

My Minecraft is just haunted, I guess!

**Comment by Micalobia** [comment]
Yeah, I feel the pain of crafting your own pack, it's like diffusing a bomb at all times. I'm going to close this issue, if it comes up again I'll reopen it, what a weird bug lol

**Comment by IdrisQe** [comment]
It actually did happen again earlier, but it was in a different world (my actual survival world for this pack)

Still no idea about the cause, honestly it's probably some performance mod I have installed messing with things. I tried F3+T but it didn't fix it. Thankfully it's pretty easy to work around, I just need to occasionally slightly change how I was going to build something, and the occasional hard-to-reproduce rendering issue is totally worth the mod-compatible, seamless slab merging and vertical slabs! Like really, I'm still finding more ways to be amazed at this mod, you're a wizard!

**Comment by K0-RR** [comment]
Can you post all mods names you are using?

**Comment by IdrisQe** [comment]
I could but it's an incredibly massive list unfortunately ._. So finding out what's causing the problem would be a lot of work.

**Comment by Neeko-iko** [comment]
this issue seems to still persist (please tell me this is the right issue)
im wondering if its sodium+indium or not?
![image](https://user-images.githubusercontent.com/45524401/110419035-69280680-804d-11eb-836c-367e769fa488.png)
this is me goofing around with the mod after the server fix, this seems to be consistent
i relogged from the server multiple times, the rendering error is still there
(this is with Nether brick and Terrestria japanese maple)
![image](https://user-images.githubusercontent.com/45524401/110419251-d20f7e80-804d-11eb-9416-2fb21226a651.png)
here it is with just vanilla slabs (spruce and nether brick)

**Comment by Neeko-iko** [comment]
more context- this appears to only happen on 1 side of the block.  This is me FACING positive z
the blockface is negative z if im not an idiot.
and it doesn't matter if the slab is vertical or not- the rendering error will occur regardless
edit:
it also happens with stairs facing any direction

**Comment by IdrisQe** [comment]
It's _probably_ not Sodium and Indium since I'm using neither in my current modpack (specifically because they have a tendency to bug out rendering), and yeah this seems like the right issue. Unfortunately we never did find out the cause, or a solution, and my particular case was incredibly inconsistent.

I don't suppose you have a relatively sane modlist you could post so I could compare, maybe see if we have any mods in common that could be the cause? (My list is far too big to post, and since my issue was so hit-and-miss I can't really remove mods to narrow it down)

**Comment by Neeko-iko** [comment]
my modlist is available in issue #8 where i experienced crashes solely serverside and provided a crash log.
its kinda massive though.
if you want i can go through all my Jars so that it doesn't include literally every dependency in a massive list.

**Comment by Neeko-iko** [comment]
i remembered im a ""programmer"" and am perfectly capable of writing a 3 line python script to do all of this for me.

my mods are
--
Adorn-1.13.0+1.16.5.jar
animal_feeding_trough-1.0.0.jar
antighost-1.16.5-fabric0.30.0-1.1.3.jar
appleskin-mc1.16-fabric-1.0.11.jar
artifacts-2.3.0+fabric.jar
astromine-1.11.5+fabric-1.16.5.jar
autoconfig1u-3.3.1.jar
bedspreads-fabric-1.3.1-1.16.4.jar
beenfo-1.16.5-fabric0.30.0-1.3.jar
BetterCaves-Fabric-1.16.5-1.1.jar
betterdroppeditems-1.2.4-1.16.2.jar
BetterMineshafts-Fabric-1.16.4-1.0.jar
biome_locator-1.1.2.jar
can-i-mine-this-block-1.0.2.jar
charm-fabric-1.16.5-2.3.2.jar
cinderscapes-1.3.3.jar
cleancut-mc1.16-2.1-fabric.jar
cloth-api-1.5.47.jar
cloth-config-4.11.14-fabric.jar
compressedblocks-1.0.1.jar
Couplings-1.3.6.jar
Croptopia-1.16.4-5-FABRIC-1.2.0.jar
ctm-fabric-0.3.2.jar
diggusmaximus-1.4.2-1.16.3.jar
EnchantmentDescriptions-fabric-1.16.5-2.0.1.jar
expandedstorage-5.6.33+1.16.5.jar
fabric-api-0.31.0+1.16.jar
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
flytre_lib-0.2.8.jar
full-slabs-1.3.1.jar
glassdoor-1.5.0-1.16.jar
glassential-fabric-1.16.4-1.1.5.jar
go-fish-1.2.1-beta-1.16.4.jar
Harvest-fabric-1.16.1-1.2.12-26.jar
HealthOverlay-1.16.4-2.1.7.jar
hydrogen-fabric-mc1.16.5-0.2.jar
immersive-portals-0.80-mc1.16.5-fabric.jar
indium-1.0.0.jar
inmis-2.1.2-1.16.4.jar
iron-jetpacks-0.3.1.jar
kibe-1.16.5-1.6.4-BETA.jar
lambdynamiclights-fabric-1.3.4+1.16.jar
lithium-fabric-mc1.16.5-0.6.4.jar
mocolors-1.1.0.jar
modmenu-1.16.8.jar
mousewheelie-1.6.4+mc1.16.4.jar
Origins-1.16.5-0.5.2.jar
Origins-Classes-1.16.5-1.1.1.jar
Pehkui-1.8.0+21w08b.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
pipette-2.0.0(1).jar
PresenceFootsteps-r29+1.16.4.jar
RebornCore-1.16-4.7.2+build.132.jar
red-bits-1.7.0.jar
rer-2.1.3.jar
reroll-1.2.0-1.16.5.jar
RoughlyEnoughItems-5.10.184.jar
sandwichable-1.1.2__1.16.2.jar
slimeorigin-1.0.1.jar
smootherbedrock-1.0.0.jar
sodium-fabric-mc1.16.4-0.1.1-ipc2.jar
TechReborn-1.16-3.8.1[CUSTOM].jar
terrestria-2.2.0.jar
TIS-3D-MC1.16.2-Fabric-1.6.1.23.jar
traverse-3.3.2.jar
trinkets-2.6.7.jar
walljump-fabric-1.3.3+1.16.1.jar
whereisit-1.16.5-1.11.6.jar
woodenhoppers-1.0.0.jar
wraith-waystones-1.1.1.1.jar
wthit-2.2.1+1.16.5.jar
XaerosWorldMap_1.12.1_Fabric_1.16.5.jar
Xaeros_Minimap_21.4.1_Fabric_1.16.5.jar
YungsApi-1.16.5-Fabric-2.jar

if you send your list (if you want me to drop the 3 line source code of a python script to do it for you) i can go ahead and narrow down the list automatically. shouldn't take long.

**Comment by IdrisQe** [comment]
Hmm... Disregarding libraries, the mods we have in common _seem_ to be: 
Adorn, AppleSkin, Bedspreads, YUNG's Better Caves, YUNG's Better Mineshafts, Charm, Cinderscapes, CleanCut, Croptopia, Enchantment Descriptions, Full Slabs (obviously), Immersive Portals (though I didn't have it when I was first having these issues), Lithium, Mouse Wheelie, Patchouli, Pehkui, Phosphor, Reroll, REI, Terrestria, Traverse, Trinkets, Waystones, Xaero's Minimap, and Xaero's World Map...

Most of these shouldn't really affect block rendering in any way... I feel like the only possible causes, or heck, the only ones that I would imagine touch world rendering in ANY weird ways are Lithium and Phosphor... Since they're kinda invasive like Sodium, though to a lesser degree.

Honestly I just didn't want to leave a massive wall of text and a modlist too large to ever reasonably be tested against, but since this is still happening, I might as well post it. Apologies in advance, there's not gonna be any nice formatting here.

accurate-block-placement-1.0.9.jar
Adorn-1.13.0+1.16.5.jar
Allure-1.2.8.jar
appleskin-mc1.16-fabric-1.0.11.jar
aquarius-1.0.3.jar
architectury-1.8.128-fabric.jar
backslot-1.1.9.jar
banner_capes-0.2.1.jar
bedrockify-0.2.5-1.16.2+.jar
bedspreads-fabric-1.3.1-1.16.4.jar
better-end-0.9.1-pre.jar
better-nether-5.0.7.jar
betterbiomeblend-1.16.4-1.1.3-fabric.jar
BetterCaves-Fabric-1.16.5-1.1.jar
BetterMineshafts-Fabric-1.16.4-1.0.1.jar
betterthanmending-1.3.0.jar
BetterThirdPerson-Fabric-1.16.4-1.4.0.jar
bewitchment-1.16.5-5.jar
biome-makeover-1.16.4-1.2.11.jar
campanion-1.3.5.jar
carpet-extra-1.16.5-1.4.27.jar
castle_dungeons-2.2-1.16.5-fabric.jar
ce_foodstuffs-1.1.3.jar
charm-fabric-1.16.5-2.3.2.jar
charmonium-fabric-1.16.5-2.3.2.jar
cinderscapes-1.3.3.jar
ClassicalArt-1.16.2+-1.1.0.jar
cleancut-mc1.16-2.1-fabric.jar
clear-skies-mc116-1.5.55.jar
cloth-config-4.11.14-fabric.jar
cpas-1.3.0+1.16.5.jar
creeper-spores-1.4.1.jar
Croptopia-1.16.4-5-FABRIC-1.2.0.jar
crowmap-1.16.2-1.0.1.jar
crumbs-fabric-1.0.7.jar
cullleaves-2.1.0.jar
curses-mod-1.5.1.jar
darkness-mc116-1.6.58.jar
DarkPaintings-fabric-1.16.5-3.0.1.jar
data-loader-2.1.0+mc1.16.1.jar
dawn-1.7.jar
desolation-1.1.0.jar
DualRiders-1.0.5.jar
DynamicSoundFilters-1.2.0+1.16.5.jar
EnchantmentDescriptions-fabric-1.16.5-2.0.1.jar
enhanced_attack_indicator-1.0.0+1.16.jar
EntityCulling-Fabric-1.0.3.jar
extraalchemy-fabric-1.16.5-1.4.1.jar
ExtraDoors-1.8.2-1.16.2.jar
Fabric-1.16.5-TillItBreaks-0.1.jar
fabric-api-0.31.0+1.16.jar
fabric-carpet-1.16.5-1.4.28+v210224.jar
fabric-language-kotlin-1.4.30+build.2.jar
fabrication-1.3.4.jar
FallingTree-Fabric-1.16.5-2.10.2.jar
ferritecore-2.0.3-fabric.jar
full-slabs-1.3.1.jar
geckolib-fabric-1.16.5-3.0.22.jar
HealthOverlay-1.16.4-3.6.14.jar
herdspanic-1.0.1.jar
horse-stats-vanilla-4.1.7.jar
i-am-very-smart-2.1.0+mc1.16.1.jar
illuminations-1.4.5.jar
immersive-portals-0.80-mc1.16.5-fabric.jar
Impersonate-2.1.0.jar
item-model-fix-1.0.0.jar
krypton-0.1.2.jar
Lakeside-1.0.3+1.16.4.jar
lazydfu-0.1.2.jar
lepton-fabric-1.16.5-1.0.0.jar
LessAnnoyingPiglins-1.0.1.jar
light-overlay-5.8.0.jar
lithium-fabric-mc1.16.5-0.6.4.jar
Loading-Timer-1.2.1.jar
lock_minecart_view-for-MC1.16.2-1.2.1.jar
microDurability-0.3.1+1.16.3.jar
mini-extras-fabric-1.2.1.jar
mobblindness-1.0.0.jar
mobs-attempt-parkour-0.2.2-1.16.5.jar
modmenu-1.16.8.jar
Monster-of-the-ocean-depths-3.1-1.16.5.jar
morerespawnanchors-1.0.1.jar
mostructures-1.1.0+mc.1.16.5.jar
mousewheelie-1.6.4+mc1.16.4.jar
music-duration-reducer-1.2.0.jar
nookbuild-1.4.0.jar
notenoughcrashes-3.1.8-fabric.jar
OverpoweredMending-Fabric-1.16.5-2.2.3.jar
overworld-two-1.0.4.jar
Patchouli-1.16.4-50-FABRIC.jar
peepingcreepers-fabric-1.1.jar
Pehkui-1.7.1+21w03a.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
polymorph-fabric-0.0.10-1.16.5.jar
potiondescriptions-1.16.3-fabric-1.1.jar
PresenceFootsteps-r29+1.16.4.jar
randompatches-2.4.5-fabric.jar
ratsmischief-1.0.3.jar
repurposed_structures-1.16.5-1.8.6.jar
requiem-1.5.0.jar
reroll-1.2.0-1.16.5.jar
riverredux-0.1.6.jar
RoughlyEnoughItems-5.10.184.jar
SakuraRosea-1.6.0-MC1.16.3-fabric.jar
SaveMyStronghold-Fabric-1.16.4-1.0.jar
shulkercharm-1.1.3+1.16.5.jar
smoothboot-fabric-1.16.5-1.5.0.jar
somnus-fabric-0.0.11-1.16.5.jar
spellbound-1.2.0.jar
stepup-1.16.5-fabric0.30.0-1.1.jar
SurvivalAdditions-1.3.2-Fabric-1.16.5.jar
terrestria-2.2.0.jar
the_bumblezone_fabric-1.16.5-2.3.0.jar
tinytweaks-1.2.3.jar
torohealth-1.16.4-fabric-4.jar
traverse-3.3.2.jar
trinkets-2.6.7.jar
UnforgivingVoid-2.0.0.jar
vanguard-uninstaller.jar
vanillaplusbiomes-0.3.0.jar
VanillaTweaks-1.16.4-1.0.6.jar
villagernames-1.16.4-1.6.0.jar
WildWorld-2.0.0+1.16.5.jar
wild_explorer-1.3.2.jar
wraith-waystones-1.1.1.1.jar
XaerosWorldMap_1.12.1_Fabric_1.16.5.jar
Xaeros_Minimap_21.4.1_Fabric_1.16.5.jar
YungsApi-1.16.5-Fabric-2.jar

**Comment by Micalobia** [comment]
This is by far the strangest bug I've hit so far, I'm not gonna lie. Cross-referenced both mod lists and installed all the mods that both of you had, and I still couldn't replicate it, so the only thing I can realistically think of is that there's a platform difference? Are both of you on Windows, or something else like Linux or MacOS?

**Comment by IdrisQe** [comment]
This is bizzare... I'm using Windows 10.
Maybe it has to do with... Java version... Or JVM Arguments? I dunno I'm just spitballing here.

Using Java 8 version 281 personally.

Arguments are:
-XMS:4G -XMX:4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

I have no idea if any of this may somehow be affecting it.

**Comment by Micalobia** [comment]
Working on completely rewriting how the mod handles slab models, as there were a few other bugs with it (glass slabs had problems because of transparency) and it was collectively just a mess to fix things, let me know if that rewrite fixes the bug (it'll be released as 2.0.0 soon, as I've started moving some of the code to a library mod)

**Comment by Micalobia** [comment]
Version 2.0.0 is out now, let me know if issues persist.

**Comment by Neeko-iko** [comment]
> 
> 
> This is by far the strangest bug I've hit so far, I'm not gonna lie. Cross-referenced both mod lists and installed all the mods that both of you had, and I still couldn't replicate it, so the only thing I can realistically think of is that there's a platform difference? Are both of you on Windows, or something else like Linux or MacOS?

sorry for the very late response, im on Windows 10
the server that i play on is using linux, but im sure you're already aware thanks to the crash report i sent in previously.

im glad to hear 2.0.0 is out now!
i'll do some testing to see if any of the rendering errors are fixed.
thank you much for your help

**Comment by Micalobia** [comment]
Going to close this issue; If that's in error, I'll reopen it, but as of right now I'm assuming I've fixed it.
