### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by Lukebb04** [Micalobia/Full-Slabs#63]
Minecraft now uses Java 17

**Comment by Micalobia** [comment]
This is waiting on this issue: https://github.com/Virtuoel/Statement/issues/12
Once that's resolved, I can update this mod to be 1.18, until then I'm sort of stuck, which is a shame.

**Comment by xanthian** [comment]
this makes me a very sad panda, i'm waiting.. hoping.. before I upgrade to 1.18

**Comment by xanthian** [comment]
It's fixed!!
