### ISSUE TITLE
:cry: 1.18.1 Crash - possibly Wthit..

### ISSUE THREAD

**Issue by xanthian** [Micalobia/Full-Slabs#66]
---- Minecraft Crash Report ----
// You're mean.

Time: 12/29/21, 10:55 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "com.mojang.datafixers.util.Pair.getSecond()" because "pair" is null
	at dev.micalobia.full_slabs.block.ExtraSlabBlock.method_9574(ExtraSlabBlock.java:122)
	at mcp.mobius.waila.data.DataAccessor.setState(DataAccessor.java:192)
	at mcp.mobius.waila.data.DataAccessor.set(DataAccessor.java:172)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:64)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:63)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$1(FabricWailaClient.java:29)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bac000$onEndTick(class_310.java:7997)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.micalobia.full_slabs.block.ExtraSlabBlock.method_9574(ExtraSlabBlock.java:122)
	at mcp.mobius.waila.data.DataAccessor.setState(DataAccessor.java:192)
	at mcp.mobius.waila.data.DataAccessor.set(DataAccessor.java:172)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:64)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:63)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$1(FabricWailaClient.java:29)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bac000$onEndTick(class_310.java:7997)

-- Affected level --
Details:
	All players: 1 total; [class_746['XanthianX'/343, l='ClientLevel', x=88.73, y=60.50, z=131.46]]
	Chunk stats: 4096, 1023
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,64,96), Section: (at 0,0,0 in 8,4,6; chunk contains blocks 128,-64,96 to 143,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 67019489 game time, 74369101 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks_r406006.zip, Fabric Mods, Icons+1.6+§f󰈔§r.zip, illuminations/lowerres, continuity/glass_pane_culling_fix, Golden+Netherite.zip, cullleaves/smartleaves, Lithos-Font+v11+for+1.17.1+.zip, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 619054800 bytes (590 MiB) / 1988100096 bytes (1896 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f02
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9676
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37563.54
	Virtual memory used (MB): 18355.22
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 48.88
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms5120m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancedcompass: Advanced Compass 1.2.6
		advancementplaques: Advancement Plaques 1.4.3
		ae2: Applied Energistics 2 10.0.0-beta.2
		alternatecurrent: Alternate Current 1.1.0
		architectury: Architectury 3.3.5
		balm-fabric: Balm 2.3.0+0
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		catwalksinc: Catwalks Inc. 1.1.0
		cem: Custom Entity Models 0.7.0
		clear-skies: Clear Skies 2.0.88
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collective-fabric: Collective (Fabric) 3.14
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		compactstatuseffects: Compact Status Effects 2.1.0
		consistency_plus: Consistency Plus 0.4.3+1.18
		continuity: Continuity 1.0.3+1.18
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		darkness: True Darkness 2.0.89
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		eatinganimationid: Eating Animation 1.2
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fpsreducer: FPS Reducer 1.25-mc1.18
		full_slabs: FullSlabs 3.3.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.23
		highlighter: Highlighter 1.1.2
		hologram-api: Hologram API 0.2.1+1.18-pre5
		horizontalpanes: Horizontal Panes 1.1.6
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		hydrogen: Hydrogen 0.3-SNAPSHOT
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		indium: Indium 1.0.2-alpha1+mc1.18
		inventoryprofilesnext: Inventory Profiles Next 1.2.2
		invisframes: Invisible Frames 2.1.1
		itemborders: Item Borders 1.1.5
		jankson: Jankson 4.0.0+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kjsextras: KubeJS Extras 1.5.0
		krypton: Krypton 0.1.6
		kubejs: KubeJS 1801.4.0-build.254
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.5
		lenientstacksize: Lenient Stack Size 1.3.0
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.4-BETA+1.18
		lithium: Lithium 0.7.6
		loading-timer: Loading Timer 1.5
		logical_zoom: Logical Zoom 0.0.13
		lootbeams: Lootbeams 2.0.4
		magna: Magna 1.7.0-1.18-pre1
		malilib: MaLiLib 0.10.0-dev.26
		megane: megane 6.2.0
		megane-applied-energistics-2: megane-applied-energistics-2 6.2.0+10.0.0-alpha.1
		megane-base: megane-base 6.2.0
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-modern-industrialization: megane-modern-industrialization 6.2.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.2.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.2.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.2.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		micalibria: Micalibria 2.0.0
		microconfig: Microconfig 2.0.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.19.0-dev.20211204.230657
		modern_industrialization: Modern Industrialization 1.0.2
		modmenu: Mod Menu 3.0.1
		no-telemetry: No Telemetry 1.1.0
		omega-config: OmegaConfig 1.0.8
		omegamute-fabric: Omega Mute (Fabric) 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		owo: oωo 0.3.11+1.18
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		patchouli: Patchouli 1.18.1-63-FABRIC
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.4.0
		polymer: Polymer 0.2.0-beta.15+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.15+1.18.1
		pride: Pride Lib 1.1.0+1.17
		quartzelv: Quartz Elevator 2.0.1+1.18
		reborncore: Reborn Core 5.1.0-beta.4
		reeses-sodium-options: Reese's Sodium Options 1.2.4
		rhino: Rhino 1800.1.7-build.92
		ring_of_attraction: Ring Of Attraction 1.2.18
		roughlyenoughitems: Roughly Enough Items 7.1.357
		satin: Satin 1.7.0
		searchlight: Searchlight 1.1.5
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		statement: Statement 4.2.0+1.14.4-1.18.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.1.0-beta.4
		toms_storage: Tom's Simple Storage Mod 1.1.19
		tweakeroo: Tweakeroo 0.11.0
		universal-graves: Universal Graves 2.0.0-beta.3+1.18
		updateblockentity: UpdateBlockEntity 1.1.0
		valley: ValleyCraft 2.1
		windowedfullscreen: Windowed Fullscreen 1.0.0
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
		xps: Xp Obelisk 0.3.2.r_for_1.18.x_Fabric
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r406006.zip (incompatible), Fabric Mods, file/Icons+1.6+§f󰈔§r.zip, illuminations/lowerres, continuity/glass_pane_culling_fix, file/Golden+Netherite.zip (incompatible), cullleaves/smartleaves (incompatible), file/Lithos-Font+v11+for+1.17.1+.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by Micalobia** [comment]
Thankfully not Wthit, just a blunder I missed when using a middle click on it. Will be fixed in 3.3.1, working on it now
