### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by saphsara** [Micalobia/Full-Slabs#67]
Hi, Game Crashes on multiplayer when you place 2 different color slabs on top of each other and try to break them . 

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.mojang.datafixers.util.Pair.getSecond()" because "pair" is null
Exit Code: -1

**Comment by Joulanh** [comment]
Can confirm. Heres my crash log. Removing the slab-pair with /setblock minecraft:air command works fine.

I used version 3.3.1
[crash-2021-12-31_03.20.54-client.txt](https://github.com/Micalobia/Full-Slabs/files/7795163/crash-2021-12-31_03.20.54-client.txt)

**Comment by saphsara** [comment]
I will try that thank you.

**Comment by saphsara** [comment]
> 

i tried and i still crash

**Comment by saphsara** [comment]
Can confirm. Heres my crash log. Removing the slab-pair with /setblock minecraft:air command works fine.
> 
> I used version 3.3.1 [crash-2021-12-31_03.20.54-client.txt](https://github.com/Micalobia/Full-Slabs/files/7795163/crash-2021-12-31_03.20.54-client.txt)

It Still crashed when i tried this

**Comment by Micalobia** [comment]
*Should* be fixed in 3.3.2, will close unless it needs reopened

**Comment by saphsara** [comment]
Tested and works thank you for your quick response to this . Happy New Year. Have a happy and healthy year.
