### ISSUE TITLE
Missing homepage and issues tags in the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [Micalobia/Full-Slabs#7]
The homepage just redirects to the fabric website.

**Comment by Micalobia** [comment]
Must have forgotten to change the default, I'll get right on that

**Comment by Micalobia** [comment]
Should be good to go; It's in 1.3.1

**Comment by K0-RR** [comment]
Hi, just wanted to let you know the `issues` one is missing.

**Comment by K0-RR** [comment]
Oh, and the same things are missing from Micalibria.
