### ISSUE TITLE
Light passes through non luminous non opaque blocks

### ISSUE THREAD

**Issue by xanthian** [Micalobia/Full-Slabs#74]
![image](https://user-images.githubusercontent.com/7688001/148225370-bc256f0f-9caf-49ca-a58e-57aff3812b0f.png)

Glowstone (15 luminousity)
Oak Slab (0 luminousity, not opaque)

![image](https://user-images.githubusercontent.com/7688001/148225449-caca9453-0a24-4848-9c3a-bf2456c1f4d3.png)
Glowstone covered up completely, showing oak slab emitting light

![image](https://user-images.githubusercontent.com/7688001/148225519-d866e8fa-9aa1-4995-ad97-8c8495684be6.png)
Oak slab now covered also

This only occurs when the 2 slabs differ.

**Comment by Micalobia** [comment]
This happens because it makes the block in general emit light, I don't even know if I can physically make it emit light per-face, it might be a limitation of Minecraft
I will look into it though, I might've missed something
