### ISSUE TITLE
Vertical sabs do not work with Mo Glass

### ISSUE THREAD

**Issue by zaide-chris** [Micalobia/Full-Slabs#75]
It seams like Mo Glass generates horizontal glass slab textures then Full slab uses them for the vertical slabs. Full-Slabs may need to generate vertical slab glass textures to work fully with Mo Glass.

**Comment by Micalobia** [comment]
So Mo' Glass is something that needs configured, it can work
In your config folder, in `full_slabs.json`, just add these blocks to the `tiltableSlabs` section:
```json
"tiltableSlabs": [
    "minecraft:smooth_stone_slab",
    "mo_glass:glass_slab",
    "mo_glass:white_stained_glass_slab",
    "mo_glass:orange_stained_glass_slab",
    "mo_glass:magenta_stained_glass_slab",
    "mo_glass:light_blue_stained_glass_slab",
    "mo_glass:yellow_stained_glass_slab",
    "mo_glass:lime_stained_glass_slab",
    "mo_glass:pink_stained_glass_slab",
    "mo_glass:gray_stained_glass_slab",
    "mo_glass:light_gray_stained_glass_slab",
    "mo_glass:cyan_stained_glass_slab",
    "mo_glass:purple_stained_glass_slab",
    "mo_glass:blue_stained_glass_slab",
    "mo_glass:brown_stained_glass_slab",
    "mo_glass:green_stained_glass_slab",
    "mo_glass:red_stained_glass_slab",
    "mo_glass:black_stained_glass_slab"
  ]
```

**Comment by Micalobia** [comment]
Basically everything in that list will actually rotate the texture when making it go vertical, in vanilla Smooth Stone Slabs are the only one that need it.

**Comment by RotokEralil** [comment]
This works for the most part!
but there are glass slab combos that seem to still glitch
A Vertical slab in the vertical back space, with a vertical slab in the vertical right space.
This does not cause a problem in the vertical left space.
The texture on the top of the vertical back space slab, and the back of the veritcal right space slabs are missing.
There are more combos that make issues but my brain hurts trying to describe the associate positioning's sorry lol, See attached pics

![2022-01-07_19 31 35](https://user-images.githubusercontent.com/96855797/148626371-e0fb7ddf-8a07-41ed-a64f-00a091afe114.png)
![2022-01-07_19 31 30](https://user-images.githubusercontent.com/96855797/148626372-b7419c21-4077-4b5a-98c3-5c65f8fe9d97.png)
![2022-01-07_19 32 21](https://user-images.githubusercontent.com/96855797/148626373-111e8671-15fc-42d0-9720-af91f4fdc91c.png)
![2022-01-07_19 31 42](https://user-images.githubusercontent.com/96855797/148626374-5b05d51e-baad-4d93-a36d-30f47a998e1c.png)

**Comment by RotokEralil** [comment]
![2022-01-07_19 44 59](https://user-images.githubusercontent.com/96855797/148626695-21d839c2-7c59-474a-a4ac-ee620efa174e.png)

**Comment by Micalobia** [comment]
Oh that's neat, that's gonna be a tough one to patch
Will make a separate issue for it, since it's technically a different problem caused by the same mod
