### ISSUE TITLE
server crashes when trying to break a slabby block (dunno what else to call it)

### ISSUE THREAD

**Issue by Neeko-iko** [Micalobia/Full-Slabs#8]
specifically the server crashes, clients are fine

i went ahead and double checked that the server (which was running on a raspi 4) had ALL mods, in case it was missing something that the client didn't
but the server specifically still crashed.  Clients never crashed when trying to **break a block**, just the server went ahead and closed upon a player trying to break a block- the block never finished breaking, it simply just started to get broken and the server crashed instantly.

**Comment by Micalobia** [comment]
Could you give a crash report, and/or a list of mods? I don't have any issues breaking slabs on either client or server last time I checked, although I can certainly check

**Comment by Neeko-iko** [comment]
yes sir
what i find most strange is that it crashes *just* the server, the client seems to process it fine

generally we try to run the server with not clientside mods, but for this example i wanted to make sure they were both the same- as i said before.

thank you for your help, btw.
--

---- Minecraft Crash Report ----
// Sorry :(

Time: 3/7/21, 3:57 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_310
	at dev.micalobia.full_slabs.block.FullSlabBlock.method_9594(FullSlabBlock.java:100)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:751)
	at net.minecraft.class_3225.method_14263(class_3225.java:169)
	at net.minecraft.class_3244.method_12066(class_3244.java:1008)
	at net.minecraft.class_2846.method_12361(class_2846.java:40)
	at net.minecraft.class_2846.method_11054(class_2846.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version 5.10.11-v8+
	Java Version: 11.0.9.1, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Debian
	Memory: 3028662272 bytes (2888 MB) / 3833593856 bytes (3656 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx8G -Xms2M
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		amecsapi: Amecs API 1.1.3+mc1.16.5
		animal_feeding_trough: Animal Feeding Trough 1.0.0
		appleskin: AppleSkin 1.0.11
		artifacts: Artifacts 2.3.0+fabric
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.3.1-1.16.4
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		biome_locator: Biome Locator 1.1.2
		blade: Blade 2.0.0
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.5.47
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.47
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.5.47
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		couplings: Couplings 1.3.3
		croptopia: Croptopia 1.2.0
		crowdin-translate: CrowdinTranslate 1.2
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		enchantmentdescriptions: Enchantment Descriptions 2.0.1
		expandedstorage: ExpandedStorage 5.6.33
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallflyinglib: FallFlyingLib 1.1.0
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		full_slabs: Full Slabs 1.3.1
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		harvest: Harvest 1.2.12
		hydrogen: Hydrogen 0.2
		imm_ptl_core: Immersive Portals Core 0.80
		immersive_portals: Immersive Portals 0.80
		inmis: Inmis 2.1.2-1.16.4
		iron-jetpacks: Iron Jetpacks 0.3.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 11
		kibe: Kibe 1.6.4-BETA
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.4-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		lithium: Lithium 0.6.4
		magna: Magna 1.4.3-1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.5
		mocolors: Mo' Colors 1.1.0
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_joml_joml: joml 1.10.0
		origins: Origins 0.5.2
		origins-classes: Origins: Classes 1.1.1
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 1.8.0+21w08b
		phosphor: Phosphor 0.7.1+build.11
		piglib: Piglib 1.0.1
		pipette: Pipette 2.0.0
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.7.2+build.132
		redbits: Red Bits 1.7.0
		reroll: Reroll 1.2.0-1.16.5
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		sandwichable: Sandwichable 1.1.2
		slimeorigin: Slimeorigin 1.0.1
		smootherbedrock: Smoother Bedrock 1.0.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.1+build.local
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tis3d: TIS-3D 1.6.1
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweed: Tweed API 3.0.0-beta.22
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 1.1.1.1
		whereisit: Where Is It 1.11.6
		woodenhoppers: Wooden Hoppers 1.0.0
		wrenchable: Wrenchable 1.0.0+1.16.1
		wthit: wthit 2.2.1+1.16.5
		xaerominimap: Xaero's Minimap 21.4.1
		xaeroworldmap: Xaero's World Map 1.12.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Player Count: 1 / 8; [class_3222['stzz'/203, l='ServerWorld minecraft:overworld world', x=268.34, y=64.00, z=-239.03]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Micalobia** [comment]
Should be good to go in `v1.3.2`, thank you for reporting! Give me a few to get the .jar out on Curseforge and Modrinth

**Comment by Neeko-iko** [comment]
thanks so much

i'll be sure to report any other issues i have- assuming i find any!
