### ISSUE TITLE
Crash with minegate moreblocks

### ISSUE THREAD

**Issue by K0-RR** [Micalobia/Full-Slabs#9]
https://gist.githubusercontent.com/natanfudge/42e7fe9dce31b3e5eac6a6948a10e676/raw/0ece4d52c4319f2b654f4359ad5de20278f3f64f/crash.txt

**Comment by Micalobia** [comment]
Interestingly I don't get the same crash, but hopefully I've fixed this bug in 2.0.0 (coming soon), as I've moved some things around and made my mod less intrusive.

**Comment by Micalobia** [comment]
Going to close this issue, as 2.0.0 is out and I haven't heard anything; If that's in error, I'll reopen it.
